build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.12-alpine"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.12-alpine"
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine"